version: '2.1'

services:
  angular7-docker:
    image: devops-web-angular
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    command: node --inspect index.js
